"""
Trains the Decision Transformer on trajectories generated by the already-
trained Q-learning agent, then evaluates it two ways: (1) held-out
next-action prediction accuracy — the direct RL analogue of the
next-token-prediction accuracy used to evaluate language models — and
(2) a live greedy rollout in the actual environment, to confirm the
learned policy really reaches the goal, not just fits the offline data.

Run: python3 train_decision_transformer.py
"""

import numpy as np
import random
from environment import GridWorld
from q_learning_agent import QLearningAgent
from decision_transformer_agent import DecisionTransformerAgent

CONTEXT_LEN = 6


def generate_trajectories(env: GridWorld, n_trajectories: int, exploration_epsilon: float = 0.15):
    """
    Uses the pre-trained Q-learning agent to generate an offline dataset.
    Some epsilon randomness is added (rather than pure greedy) so
    trajectories vary — a Decision Transformer conditions on a *target*
    return, so it needs to see a spread of returns during training, not
    N copies of the single optimal path.
    """
    agent = QLearningAgent(n_states=env.n_states, n_actions=env.action_space_n)
    agent.load("/home/claude/self-learning-ai/python/q_table_trained.npy")
    agent.epsilon = exploration_epsilon

    trajectories = []
    for _ in range(n_trajectories):
        state = env.reset()
        states, actions, rewards = [], [], []
        done = False
        while not done:
            state_idx = env.state_to_index(state)
            action = agent.choose_action(state_idx)
            next_state, reward, done, info = env.step(action)
            states.append(env.state_to_vector(state))
            actions.append(action)
            rewards.append(reward)
            state = next_state
        trajectories.append({"states": states, "actions": actions, "rewards": rewards})
    return trajectories


def compute_returns_to_go(rewards):
    rtg = np.zeros(len(rewards))
    running = 0.0
    for t in reversed(range(len(rewards))):
        running += rewards[t]
        rtg[t] = running
    return rtg


def make_training_windows(trajectories, context_len):
    """Slices each trajectory into causal windows of length <= context_len,
    padding the start with the START token where a trajectory is shorter
    than the context so far."""
    windows = []
    for traj in trajectories:
        rtg = compute_returns_to_go(traj["rewards"])
        states = traj["states"]
        actions = traj["actions"]
        T = len(actions)
        for end in range(1, T + 1):
            start = max(0, end - context_len)
            window_rtg = list(rtg[start:end])
            window_states = states[start:end]
            window_actions_true = actions[start:end]
            window_prev_actions = [actions[i - 1] if i > start else -1 for i in range(start, end)]
            windows.append({
                "rtg": window_rtg,
                "states": window_states,
                "prev_actions": window_prev_actions,
                "true_actions": window_actions_true,
            })
    return windows


def train_decision_transformer(n_episodes_data=600, n_train_steps=8000):
    env = GridWorld(size=5, max_steps=100)

    print(f"Generating {n_episodes_data} offline trajectories from the trained Q-learning agent...")
    trajectories = generate_trajectories(env, n_episodes_data)
    returns = [sum(t["rewards"]) for t in trajectories]
    print(f"  Return range in dataset: {min(returns):.1f} to {max(returns):.1f} (avg {np.mean(returns):.1f})")

    all_windows = make_training_windows(trajectories, CONTEXT_LEN)
    split = int(len(all_windows) * 0.9)
    random.shuffle(all_windows)
    train_windows, held_out_windows = all_windows[:split], all_windows[split:]
    print(f"  {len(train_windows)} training windows, {len(held_out_windows)} held-out windows\n")

    agent = DecisionTransformerAgent(context_len=CONTEXT_LEN, learning_rate=0.001)

    print("Training Decision Transformer (supervised sequence prediction)...")
    losses = []
    for step in range(n_train_steps):
        window = random.choice(train_windows)
        loss = agent.train_step(
            window["rtg"], window["states"], window["prev_actions"], window["true_actions"]
        )
        losses.append(loss)

        if (step + 1) % 1000 == 0:
            print(f"  Step {step + 1:5d} | Avg loss (last 1000): {np.mean(losses[-1000:]):.4f}")

    return agent, env, held_out_windows


def evaluate_held_out_accuracy(agent: DecisionTransformerAgent, held_out_windows):
    """Next-action prediction accuracy on trajectory windows the model never trained on —
    directly analogous to next-token accuracy for a language model."""
    correct, total = 0, 0
    for window in held_out_windows:
        logits = agent.forward(window["rtg"], window["states"], window["prev_actions"])
        predicted_last = np.argmax(logits[-1])
        true_last = window["true_actions"][-1]
        correct += int(predicted_last == true_last)
        total += 1
    return correct / total


def evaluate_live_rollout(agent: DecisionTransformerAgent, env: GridWorld, target_return: float = 49.2):
    """Runs the DT live in the real environment: feed a target return-to-go,
    let it pick actions autoregressively, decrement the target by the reward
    actually received, and see if it reaches the goal — not fitting offline
    data, actually acting."""
    state = env.reset()
    rtg_history = [target_return]
    state_history = [env.state_to_vector(state)]
    prev_action_history = [-1]

    path = [state]
    done = False
    steps = 0
    while not done and steps < 30:
        window_rtg = rtg_history[-CONTEXT_LEN:]
        window_states = state_history[-CONTEXT_LEN:]
        window_prev_actions = prev_action_history[-CONTEXT_LEN:]

        action = agent.predict_action(window_rtg, window_states, window_prev_actions)
        next_state, reward, done, info = env.step(action)
        steps += 1
        path.append(next_state)

        rtg_history.append(rtg_history[-1] - reward)
        state_history.append(env.state_to_vector(next_state))
        prev_action_history.append(action)

        state = next_state

    return path, steps, info.get("event")


if __name__ == "__main__":
    agent, env, held_out_windows = train_decision_transformer()

    print("\n" + "=" * 60)
    print("EVALUATION")
    print("=" * 60)

    held_out_acc = evaluate_held_out_accuracy(agent, held_out_windows)
    print(f"\nHeld-out next-action prediction accuracy: {held_out_acc * 100:.1f}%")
    print("(this is the RL analogue of next-token prediction accuracy for a language model)")

    print("\nLive rollout in the real environment (target return-to-go = 49.2, the known optimal):")
    path, steps, event = evaluate_live_rollout(agent, env, target_return=49.2)
    print(f"  Path: {path}")
    print(f"  Steps: {steps}, outcome: {event}")

    print("\nLive rollout with a suboptimal target return-to-go = 30.0 (testing return-conditioning):")
    env.reset()
    path2, steps2, event2 = evaluate_live_rollout(agent, env, target_return=30.0)
    print(f"  Path: {path2}")
    print(f"  Steps: {steps2}, outcome: {event2}")
